apiVersion: apps/v1
kind: Deployment
metadata:
  name: article
spec:
  selector: 
    matchLabels: 
      app: article 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: article
    spec:
      containers:
      - name: article
        image: com.puneet.k8s/word-server:1.0
        env:
        - name: PROFILE_VALUE
          value: "article"
        - name: SERVER_PORT
          value: "8201"
        ports: 
        - containerPort: 8201
