apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence
spec:
  selector: 
    matchLabels: 
      app: sentence
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: sentence
    spec:
      containers:
      - name: sentence
        image: com.puneet.k8s/sentence-server:1.0
        env:
        - name: SERVER_PORT
          value: "8205"
        ports: 
        - containerPort: 8205
