apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject
spec:
  selector: 
    matchLabels: 
      app: subject 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: subject
    spec:
      containers:
      - name: subject
        image: com.puneet.k8s/word-server:1.0
        env:
        - name: PROFILE_VALUE
          value: "subject"
        - name: SERVER_PORT
          value: "8203"
        ports: 
        - containerPort: 8203
