apiVersion: v1
kind: Service
metadata:
  name: adjective
  labels:
    app: adjective
spec:
  type: NodePort
  ports:
  - port: 8200
    nodePort: 32000
    protocol: TCP
  selector:
    app: adjective
