kubectl delete service adjective 
kubectl delete service article 
kubectl delete service noun
kubectl delete service subject 
kubectl delete service verb 
kubectl delete service sentence 
kubectl delete deployment adjective 
kubectl delete deployment article 
kubectl delete deployment noun 
kubectl delete deployment subject 
kubectl delete deployment verb 
kubectl delete deployment sentence 
